---
sr-due: 2025-04-12
sr-interval: 4
sr-ease: 270
---

#review 
There is no single correct approach to handling errors in a program. Programs designed to provide some persistent service like a web server should be robust to errors, logging them for later consideration but continuing to service new requests as long as possible. On the other hand, the Python interpreter handles errors by terminating immediately and printing an error message, so that programmers can address issues as soon as they arise.

_Exceptions_, the topic of this section, provides a general mechanism for adding error-handling logic to programs. _Raising an exception_ is a technique for interrupting the normal flow of execution in a program, signaling that some exceptional circumstance has arisen, and <span style="background:#d3f8b6">returning directly to an enclosing part</span> of the program that was designated to react to that circumstance.Users can also raise exceptions with raise and assert statements.

**Raising exceptions.** An exception is a <span style="background:#d3f8b6">object instance with a class that inherits</span>, either directly or indirectly, from the BaseException class. The assert statement introduced in Chapter 1 raises an exception with the class AssertionError. In general, any exception instance can be raised with the raise statement. The general form of raise statements are described in the [Python docs](http://docs.python.org/py3k/reference/simple_stmts.html#raise). The most common use of raise constructs an exception instance and raises it. When an exception is raised, no further statements <span style="background:#d3f8b6">in the current block of code</span> are executed.
Unless the exception is _handled_ (described below), the interpreter will return directly to the interactive read-eval-print loop, or terminate entirely if Python was started with a file argument. *In other words*, if you are just directly interacting with Python Interpreter in Terminal, it can wait for your fixing the problem, but if you are running code from a source file, the whole process will be shut down.

**Handling exceptions.** An exception can be handled by an enclosing try statement. A try statement consists of multiple clauses; the first begins with try and the rest begin with except:
```
try:
    <try suite>
except <exception class> as <name>:
    <except suite>
...
```

### 3.3.1   Exception Objects

Exception objects themselves can have attributes, such as the error message stated in an assert statement and information about where in the course of execution the exception was raised. User-defined exception classes can have additional attributes.

The following example defines an exception class that returns the best guess discovered in the course of iterative improvement whenever a ValueError occurs. A math domain error (a type of ValueError) is raised when sqrt is applied to a negative number. This exception is handled by raising an IterImproveError that stores the <span style="background:#d3f8b6">most recent guess</span> from Newton's method as an attribute.
```python
>>> class IterImproveError(Exception):
        def __init__(self, last_guess):
            self.last_guess = last_guess
```

```python
>>> def improve(update, done, guess=1, max_updates=1000):
        k = 0
        try:
            while not done(guess) and k < max_updates:
                guess = update(guess)
                k = k + 1
            return guess
        except ValueError:
            raise IterImproveError(guess)
>>> def find_zero(f, guess=1):
        def done(x):
            return f(x) == 0
        try:
            return improve(newton_update(f), done, guess)
        except IterImproveError as e:
            return e.last_guess
```
















